baseURL = "https://cureme.cc"
languageCode = "zh-cn"
title = "Mys"
theme = "archie"
copyright = "© 你的名字"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
[params]
	mode="auto"
	featherIconsCDN=true
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://github.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Categories"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Links"
url = "/links"
weight = 5

[pagination]
  pagerSize = 5 # articles per page